function M = trympcmodels(model_name) %#ok<STOUT>
   arguments
      model_name (1,1) string ...
         {mustBeMember(model_name,[...
         "CSTR_ex1",...
         "CSTR_ex2",...
         "Pendulum_on_Cart",...
         ])}
   end

   eval("trympc_MODEL_"+model_name)

end